language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env:
        - DEPS=lowest
    - php: 5.3
      env:
        - DEPS=latest
    - php: 5.4
      env:
        - DEPS=lowest
    - php: 5.4
      env:
        - DEPS=latest
    - php: 5.5
      env:
        - DEPS=lowest
    - php: 5.5
      env:
        - DEPS=latest
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=latest
    - php: 7.0
      env:
        - DEPS=lowest
    - php: 7.0
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=latest

before_script:
  - composer self-update
  - composer install --dev --prefer-source

script:
  - phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src/

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false
