<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SlmQueueBeanstalkd\Module'                            => __DIR__ . '/Module.php',
    'SlmQueueBeanstalkd\Controller\WorkerController'       => __DIR__ . '/src/SlmQueueBeanstalkd/Controller/WorkerController.php',
    'SlmQueueBeanstalkd\Factory\BeanstalkedOptionsFactory' => __DIR__ . '/src/SlmQueueBeanstalkd/Factory/BeanstalkdOptionsFactory.php',
    'SlmQueueBeanstalkd\Factory\PheanstalkFactory'         => __DIR__ . '/src/SlmQueueBeanstalkd/Factory/PheanstalkFactory.php',
    'SlmQueueBeanstalkd\Factory\TubeFactory'               => __DIR__ . '/src/SlmQueueBeanstalkd/Factory/TubeFactory.php',
    'SlmQueueBeanstalkd\Factory\WorkerFactory'             => __DIR__ . '/src/SlmQueueBeanstalkd/Factory/WorkerFactory.php',
    'SlmQueueBeanstalkd\Job\Exception\BuryableException'   => __DIR__ . '/src/SlmQueueBeanstalkd/Job/Exception/BuryableException.php',
    'SlmQueueBeanstalkd\Job\Exception\ReleasableException' => __DIR__ . '/src/SlmQueueBeanstalkd/Job/Exception/ReleasableException.php',
    'SlmQueueBeanstalkd\Options\BeanstalkdOptions'         => __DIR__ . '/src/SlmQueueBeanstalkd/Options/BeanstalkdOptions.php',
    'SlmQueueBeanstalkd\Options\ConnectionOptions'         => __DIR__ . '/src/SlmQueueBeanstalkd/Options/ConnectionOptions.php',
    'SlmQueueBeanstalkd\Queue\Tube'                        => __DIR__ . '/src/SlmQueueBeanstalkd/Queue/Tube.php',
    'SlmQueueBeanstalkd\Queue\TubeInterface'               => __DIR__ . '/src/SlmQueueBeanstalkd/Queue/TubeInterface.php',
    'SlmQueueBeanstalkd\Service\PheanstalkService'         => __DIR__ . '/src/SlmQueueBeanstalkd/Service/PheanstalkService.php',
    'SlmQueueBeanstalkd\Version'                           => __DIR__ . '/src/SlmQueueBeanstalkd/Version.php',
    'SlmQueueBeanstalkd\Worker\Worker'                     => __DIR__ . '/src/SlmQueueBeanstalkd/Worker/Worker.php',
);